This notebook is showing some operations on tensors that are really important to understand when working with Machine Learning

In [76]:
from numpy import array
from numpy import tensordot
import numpy as np

In [7]:
# This is in fact a scalar, by default tensors are named with Capitol Characters in some code conventions
T_0 = array(1)

In [8]:
T_0.ndim

0

Next Tensor has 2 items with each 3 parameters: House - nr of rooms, square footage house, square footage total

In [42]:
T_input_house = array([[3,110,200],[4,99,250]])

In [43]:
T_input_house.shape

(2, 3)

Define a set of images by their color using a code from 0-255

In [18]:
T_input_image = array(
    [
        [[128,10,0],[50,100,150]],
        [[128,10,128],[50,100,100]]
    ]
)

In [20]:
T_input_image.shape

(2, 2, 3)

Some of the operations that are possible:
- Add Tensors of same range as well as shape or with the right shape also with tensors of different range

In [34]:
array([1,2]) + array([3,4])

array([4, 6])

In [40]:
array([1,2,4]) + array([2,3])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [41]:
array([1,2,3]) + array([[2],[3]])

array([[3, 4, 5],
       [4, 5, 6]])

In [38]:
array([1,2]) * 3

array([3, 6])

In [35]:
array([1,2]) * array([3,4])

array([3, 8])

In [37]:
array([1,2]) + array([[3],[4]])

array([[4, 5],
       [5, 6]])

In [71]:
array([1,2]).dot(array([2,3]))

8

In [33]:
array([1,1]).dot(array([[2,2],[4,5]]))

array([6, 7])

In [75]:
tensordot(array([1,2]), array([3,4]), axes=0)

array([[3, 4],
       [6, 8]])

Why is this so important? When we get to using deep learning with neural networks it becomes evident

Each layer transforms the data using a number of weights. Imagine we have a two layer network. Each layer consisting of 2 nodes. The network has one output and three inputs. The output is the price of a house, the input is the number of rooms, square footage of the house and overall.

In [54]:
T_weights_house = array([[1.1,0.5],[1.0,0.3],[0.7,0.11]])

In [55]:
print(T_weights_house.ndim)
print(T_weights_house.shape)

2
(3, 2)


In [78]:
def relu(data):
    return np.maximum(data, 0.)

In [79]:
T_output_layer_1 = relu(T_input_house.dot(T_weights_house))
print(T_output_layer_1)

[[253.3  56.5]
 [278.4  59.2]]


In [80]:
T_weights_layer_2 = array([[0.01,0.02],[0.03,0.04]])

In [82]:
T_output_layer_2 = relu(T_output_layer_1.dot(T_weights_layer_2))
print(T_output_layer_2)

[[4.228 7.326]
 [4.56  7.936]]


In [77]:
np.relu(T_output_layer_2)

AttributeError: module 'numpy' has no attribute 'relu'