This notebook is showing some operations on tensors that are really important to understand when working with Machine Learning

In [ ]:
from numpy import array
from numpy import tensordot
import numpy as np

In [ ]:
# This is in fact a scalar, by default tensors are named with Capitol Characters in some code conventions
T_0 = array(1)

In [ ]:
T_0.ndim

Next Tensor has 2 items with each 3 parameters: House - nr of rooms, square footage house, square footage total

In [ ]:
T_input_house = array([[3,110,200],[4,99,250]])

In [ ]:
T_input_house.shape

Define a set of images by their color using a code from 0-255

In [ ]:
T_input_image = array(
    [
        [[128,10,0],[50,100,150]],
        [[128,10,128],[50,100,100]]
    ]
)

In [ ]:
T_input_image.shape

Some of the operations that are possible:
- Add Tensors of same range as well as shape or with the right shape also with tensors of different range

In [ ]:
array([1,2]) + array([3,4])

In [ ]:
array([1,2,4]) + array([2,3])

In [ ]:
array([1,2,3]) + array([[2],[3]])

In [ ]:
array([1,2]) * 3

In [ ]:
array([1,2]) * array([3,4])

In [ ]:
array([1,2]) + array([[3],[4]])

In [ ]:
array([1,2]).dot(array([2,3]))

In [ ]:
array([1,1]).dot(array([[2,2],[4,5]]))

In [ ]:
tensordot(array([1,2]), array([3,4]), axes=0)

Why is this so important? When we get to using deep learning with neural networks it becomes evident

Each layer transforms the data using a number of weights. Imagine we have a two layer network. Each layer consisting of 2 nodes. The network has one output and three inputs. The output is the price of a house, the input is the number of rooms, square footage of the house and overall.

In [ ]:
T_weights_house = array([[1.1,0.5],[1.0,0.3],[0.7,0.11]])

In [ ]:
print(T_weights_house.ndim)
print(T_weights_house.shape)

In [ ]:
def relu(data):
    return np.maximum(data, 0.)

In [ ]:
T_output_layer_1 = relu(T_input_house.dot(T_weights_house))
print(T_output_layer_1)

In [ ]:
T_weights_layer_2 = array([[0.01,0.02],[0.03,0.04]])

In [ ]:
T_output_layer_2 = relu(T_output_layer_1.dot(T_weights_layer_2))
print(T_output_layer_2)

In [ ]:
np.relu(T_output_layer_2)